#!/bin/sh

set -e

font="misc"

if [ "$1" = "remove" ]; then
  if [ -x /usr/X11R6/bin/mkfontdir ]; then
    for i in $font; do
      dir=/usr/X11R6/lib/X11/fonts/$i
      if [ -d $dir ]; then
	echo Adjusting font index in $dir...
        (cd $dir; /usr/X11R6/bin/mkfontdir)
      fi
    done
  fi
fi

#DEBHELPER#

